### ISSUE TITLE
timeout with ban question

### ISSUE THREAD

**Issue by RusAlex** [kak-tus/irma_bot#1]
Please can we use Timeout variable to auto ban users who did not responded to a ban question?

**Comment by kak-tus** [comment]
You want to setup timeout in chat settings for main Irma bot? Or you want ability to set timeout in selfhosted Irma instance?

**Comment by RusAlex** [comment]
Thank you for answering fast. Well I'm not good Go developer. At moment I'm using main bot. And would like not to run my own instance for bot. Yours works well. If you could add the option to main bot, I wait for this. But also I could amend the code and just change it for myself and run my own bot.

**Comment by kak-tus** [comment]
I will add it as chat settings.

**Comment by kak-tus** [comment]
@RusAlex Ready. Try send in chat
```
@irma_bot set_ban_timeout 5
```
 5 - timeout in minutes.

**Comment by RusAlex** [comment]
good it responded. thanks
